# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


def fibo(n)
  n <= 1 ? n : fibo(n-1) + fibo(n-2)
end

def sum_of_evens(max)
  arr = []
  num = 0
  value = 0
  while value < max
    arr << fibo(num) if fibo(num) % 2 == 0
    value = fibo(num)
    num += 1
  end
  arr.inject {|sum,n| sum + n}
end

